= ELN Special Interest Group

ELN SIG is a Fedora Special Interest Group which is responsible for the ELN
project and its infrastructure.

The official SIG membership list is maintained as part of our Github Organization and can be viewed https://github.com/orgs/fedora-eln/people[here].

== Responsibilities

* Own the scope and configuration of the `eln` disttag and buildroot (see
  xref:buildroot.adoc[ELN Buildroot]).

** As the project evolves the scope might change. There might be additional
   features which will be included into the tag or excluded from it.

* Define ELN content set

* Own the configuration of the compose (see xref:compose.adoc[ELN Compose]).

* Maintain infrastructure required to build packages and composes.

* Track the status of package builds and composes. Work with Fedora package
  maintainers to resolve the issues.

* Keep track of the eln-conditionals in RPM spec files.

* Investigate compose failures

* Own buildroot configuration

== Communication

* Mailing list: Add *[ELN]* to the subject of an email to the https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/[devel@ mailing list]

* Matrix Room: https://matrix.to/#/#eln:fedoraproject.org[#eln:fedoraproject.org]

* IRC was used in the past but it is not used anymore, listing here for reference: https://web.libera.chat/?channels=#fedora-eln[#fedora-eln on Libera]

=== Issue tracker

* https://github.com/fedora-eln/eln/issues

=== Meetings

Meetings of the ELN Special Interest Group are held on Fridays at noon, US Eastern Time. It is listed on the https://calendar.fedoraproject.org/SIGs/[SIGs calendar].

The meeting agenda will generally be prepared in advance by opening tickets on the https://github.com/fedora-eln/eln/issues[issue tracker] and tagging them with the `meeting` label.

== How to Join

Anyone may join the SIG by asking to become a member. If no existing SIG member *opposes* that request within a week, they're in. If an existing SIG member opposes, we will hold a regular vote at the next scheduled meeting as described above.

Prospective members may ask to join by filing a "New Member Request" ticket on the https://github.com/fedora-eln/eln/issues/new/choose[issue tracker].
